name: new
on:
  push:
    paths:
      - "!README.md"
    branches: [main]

  pull_request:
    types: [opened,reopened,synchronize,labeled,unlabeled]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
